---
- name: Deploying Artifact
  hosts: webservers
  become: yes
  become_user: root
  tasks:
  - name: Copy file
    copy :
      src: /opt/jenkins/workspace/java-pipeline/target/springboot-bootcamp-0.0.1-SNAPSHOT.jar
      dest: /home/ubuntu
  - name: Update APT package manager repositories cache
    apt:
      update_cache: yes
  - name: Install Java using Ansible
    apt:
      name: openjdk-11-jdk
      state: present
  - name: Running Artifact
    shell: nohup java -jar /home/ubuntu/springboot-bootcamp-0.0.1-SNAPSHOT.jar &
